apiVersion: v2
name: gitea-mirror
description: Kubernetes helm chart for gitea-mirror
type: application
version: 0.0.1
appVersion: 3.7.2
icon: https://github.com/RayLabsHQ/gitea-mirror/blob/main/.github/assets/logo.png
keywords:
  - git
  - gitea
sources:
  - https://github.com/RayLabsHQ/gitea-mirror
maintainers:
  - name: Paulo Machado
    email: pffmachado@gmail.com