name: cdash
description: A Helm Chart for CDash
version: 0.9.25
icon: https://www.cdash.org/wp-content/uploads/2019/05/slider-cdash.png
apiVersion: v2
keywords:
  - cdash
home: https://www.cdash.org
sources:
  - https://github.com/Kitware/CDash
maintainers:
  - name: Paulo Machado
    email: pffmachado@gmail.com
